name: Actualizar datos de cortes
on:
  schedule:
    - cron: '0 */2 * * *'  # Cada 2 horas
  workflow_dispatch:       # Permite ejecución manual

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install telethon requests

      - name: Run scraping script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: |
          python scripts/scrape_and_update.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push changes
        run: |
          git add data/cortes.json
          git commit -m "Actualización automática de cortes: $(date +'%Y-%m-%d %H:%M')"
          git push
