name: Actualización Multi-Provincial
on:
  schedule:
    - cron: '*/45 * * * *'  # Ejecutar cada 45 minutos
  workflow_dispatch:        # Permite ejecución manual

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Permisos explícitos de escritura
    timeout-minutes: 15     # Nuevo: timeout para evitar ejecuciones largas

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0    # Necesario para el diff de múltiples archivos

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon requests pytz  # requests es necesario para la API de bots
          sudo apt-get install -y jq

      - name: Run multi-province scraper
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Nuevo: Token para URLs permanentes
        run: |
          # Verifica que los medios se procesen correctamente
          python scripts/scrape_and_update.py
          echo "=== Resumen de medios ==="
          find data/provincias -name "*.json" -exec grep -l "media_url" {} \; | xargs -I {} sh -c 'echo "{}: $(grep -c "media_url" {}) medios"'
          echo "========================="

      - name: Get changed provinces
        id: changes
        run: |
          # Obtiene lista de provincias y medios modificados
          git diff --name-only HEAD | grep -E 'data/provincias/.*\.json' > changed_files.txt
          if [ -s changed_files.txt ]; then
            echo "Modified provinces:"
            cat changed_files.txt
            # Extrae nombres y conteo de medios
            PROVINCIAS=$(cat changed_files.txt | sed 's|data/provincias/||;s|\.json||' | tr '\n' ', ' | sed 's/, $//')
            MEDIA_COUNT=$(cat changed_files.txt | xargs -I {} grep -c "media_url" {} | awk '{sum+=$1} END {print sum}')
            echo "::set-output name=PROVINCIAS::$PROVINCIAS"
            echo "::set-output name=MEDIA_COUNT::$MEDIA_COUNT"
          else
            echo "No changes detected"
            echo "::set-output name=PROVINCIAS::none"
            echo "::set-output name=MEDIA_COUNT::0"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.PROVINCIAS != 'none'
        run: |
          # Configuración inicial
          git config --global --add safe.directory /github/workspace
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          # Añade todos los cambios
          git add data/provincias/

          # Mensaje de commit mejorado
          COMMIT_MSG="Actualización: ${{ steps.changes.outputs.PROVINCIAS }} | ${{ steps.changes.outputs.MEDIA_COUNT }} nuevos medios - $(date +'%Y-%m-%d %H:%M %Z')"
          
          # Commit y push con control de errores
          git diff-index --quiet HEAD || {
            git commit -m "$COMMIT_MSG"
            git pull --rebase origin main
            git push origin HEAD:main
            echo "✅ Changes pushed successfully"
          }
